FROM maven:3.8.4-openjdk-17-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /app

ONBUILD COPY ./app/ ./app/

ONBUILD RUN mvn package -f app/pom.xml

ONBUILD RUN mv app/target/app.jar .

ONBUILD RUN find . -not -name app.jar -delete

CMD java -jar app.jar
