FROM maven:3.8.4-openjdk-17-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY ./app/ ./app/

RUN mvn package -f app/pom.xml

RUN mv app/target/app.jar .

RUN find . -not -name app.jar -delete

CMD java -jar app.jar