FROM node:14.17.5

SHELL ["/bin/bash", "-c"]

WORKDIR /app

ONBUILD COPY package.json .

ONBUILD COPY package-lock.json .

ONBUILD RUN ["npm", "install"]

ONBUILD COPY app/ ./app/

CMD ["node", "."]

